### ISSUE TITLE
one more thing call.js does not work error below

### ISSUE THREAD

**Issue by dog1cool** [thurdev/AyxBot#8]
```js

(node:133) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'send' of undefined
    at /home/runner/AyxBot/commands/call.js:118:17
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:133) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
{
  body: { type: 'UNAUTHORIZED', error_title: 'Unauthorized' },
  headers: {
    server: 'nginx',
    date: 'Mon, 26 Jul 2021 13:49:34 GMT',
    'content-type': 'application/json',
    'content-length': '52',
    connection: 'close',
    'x-frame-options': 'deny',
    'x-xss-protection': '1; mode=block;',
    'strict-transport-security': 'max-age=31536000; includeSubdomains',
    'x-content-type-options': 'nosniff',
    'content-disposition': 'attachment; filename="api.txt"',
    'x-nexmo-trace-id': '8c091132adac5d692610df63283ae0f2'
  },
  statusCode: 401
}```

**Comment by thurdev** [comment]
Probably because of Nexmo API or you didn't had your credentials right.

**Comment by thurdev** [comment]
I'm gonna close this issue, because of the new version coming.
